import './globals.css';

import { LayoutDataProvider } from './store';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutDataProvider>
      <html lang='en'>
        <body className='container mx-auto py-16'>{children}</body>
      </html>
    </LayoutDataProvider>
  );
}
